name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test -v d --configuration Release --collect:"XPlat Code Coverage" /p:Exclude="[ActionsTest.Views.*]*
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.5.2
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'Cobertura'
        verbosity: Verbose
